markdown: redcarpet
highlighter: null
permalink: /:title

url: ycswaves.github.io/blog
baseurl: ycswaves.github.io/blog

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed